export { default as CustomGallery } from '@/components/custom-gallery/CustomGallery';
export { default as DynamicHead } from '@/components/shared/DynamicHead';
export type { GetStaticPaths, GetStaticProps } from 'next';
export type { PageProps, HomeComponentProps, RollersPageProps } from '../context/withStaticPathsAndProps';
export { default as BackCover } from '@/components/ui/back-cover/BackCover';
export { default as ButtonSubmitDrawing } from '@/components/ui/button/ButtonSubmitDrawing';
export { default as Navigation } from '@/components/ui/navigation/Navigation';
export type { HomePage } from '../../locales/types';
export { default as Heading } from '@/components/ui/typography/Heading';
export { default as Image } from 'next/image';
export { default as Paragraph } from '@/components/ui/typography/Paragraph';
export { default as Container } from '@/components/ui/container/Container';
export { default as CustomButton } from '@/components/ui/button/CustomButton';
export { default as Wrapper } from '@/components/ui/wrapper/Wrapper';
export { default as InfoCardLis } from '@/components/ui/info-card/InfoCardList';
export { default as CharacteristicsRollers } from '@/components/ui/characteristics/CharacteristicsRollers';
export { default as CustomTable } from '@/components/ui/table/CustomTable';
export { default as ProductionCapabilities } from '@/components/ui/production-capabilities/ProductionCapabilities';
export { default as CastIronRolls } from '@/components/ui/cast-iron-rolls/CastIronRolls';
export { default as TableInformation } from '@/components/ui/table-information/TableInformation';
export { default as Contacts } from '@/components/contacts/Contacts';
export { default as InfoBlock } from '@/components/ui/Info-block/InfoBlock';
